default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ralph
  password: root
  host: localhost

development:
  <<: *default
  database: manage_accounts_development

test:
  <<: *default
  database: manage_accounts_test

production:
  <<: *default
  database: manage_accounts
